apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        service: kaui
      name: kaui
    spec:
      replicas: 1
      selector:
        matchLabels:
          service: kaui
      template:
        metadata:
          creationTimestamp: null
          labels:
            service: kaui
        spec:
          containers:
            - envFrom:
              - secretRef:
                  name: kill-bill-secret
              image: killbill/kaui:2.0.11
              name: kaui
              ports:
                - containerPort: 8080
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        service: kaui
      name: kaui
    spec:
      ports:
        - name: "9090"
          port: 9090
          targetPort: 8080
      selector:
        service: kaui
      type: ClusterIP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        #nginx.ingress.kubernetes.io/rewrite-target: /$2
      name: kaui
      namespace: dev
    spec:
      ingressClassName: nginx
      rules:
      - host: cc-kaui-dev.p-s.kz
        http:
          paths:
          - backend:
             service:
                name: kaui
                port:
                  number: 9090
            path: /
            pathType: ImplementationSpecific
      tls:
      - hosts:
        - cc-dev.p-s.kz
        secretName: cert
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        service: killbill
      name: killbill
    spec:
      replicas: 1
      selector:
        matchLabels:
          service: killbill
      template:
        metadata:
          labels:
            service: killbill
        spec:
          containers:
            - envFrom:
              - secretRef:
                  name: kill-bill-secret
              image: killbill/killbill:0.24.2
              name: killbill
              ports:
                - containerPort: 8080
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        service: killbill
      name: killbill
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        service: killbill
      type: ClusterIP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        #nginx.ingress.kubernetes.io/rewrite-target: /$2
      name: killbill
      namespace: dev
    spec:
      ingressClassName: nginx
      rules:
      - host: cc-killbill-dev.p-s.kz
        http:
          paths:
          - backend:
             service:
                name: killbill
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
      tls:
      - hosts:
        - cc-dev.p-s.kz
        secretName: cert